### ISSUE TITLE
mHuBERT on ML-SUPERB benchmark using espnet with s3prl as frontend

### ISSUE THREAD

**Issue by Trikaldarshi** [utter-project/mHuBERT-147-scripts#2]
Hello,
Thanks a lot for providing details about mHuBERT training. However, I am trying to reproduce ML-SUPERB numbers for mHuBERT. I couldn't find any info/pointers in this repository. 
I am trying to use the recipes provided at https://github.com/espnet/espnet/tree/master/egs2/ml_superb/asr1
For using mHuBERT, I modified the following bit at https://github.com/espnet/espnet/blob/master/egs2/ml_superb/asr1/conf/tuning/train_asr_s3prl_single.yaml
```
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hubert_custom
        path_or_url: "mydir/checkpoint_best.pt"
        extra_conf: {"fairseq":True}
    download_dir: ./hub
    multilayer_feature: True
```
where ```path_or_url``` points out the download checkpoint from ```https://huggingface.co/utter-project/mHuBERT-147/blob/main/checkpoint_best.pt``` and as per  the s3prl upstream documentation https://s3prl.github.io/s3prl/tutorial/upstream_collection.html#hubert-custom, with ```extra_conf: {"fairseq": True}``` as you mentioned in the other issue that it is ```fairseq``` checkpoint. The above frontend configuration should convert the fairseq checkpoint to s3prl. 
However, I am getting some errors using this setup, for example:
```
/espnet/espnet2/train/trainer.py", line 161, in resume
    model.load_state_dict(states["model"], strict=strict)
RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
	size mismatch for frontend.upstream.upstream.model.label_embs_concat: copying a param with shape torch.Size([504, 256]) from checkpoint, the shape in current model is torch.Size([1004, 256]).
```
Not sure if this is related my wrong use of mHuBERT or related to espnet toolkit or s3prl toolkit. Could you please let me now how did you evaluate mHuBERT on ML-SUPERB benchmark?

**Comment by mzboito** [comment]
Hello,

Thanks for the interest in our model!
ML-SUPERB evaluation was performed using the HuggingFace interface for the model.

Here is a snippet of the config yaml:

```
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hf_hubert_custom
        path_or_url: utter-project/mHuBERT-147 # the huggingface ID (such as TencentGameMate/chinese-hubert-large)
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 768  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80
```

When launching setups, you should also make sure that "num_iters_per_epoch" corresponds to the correct task you are targeting. Its value is different for monolingual ASR, multilingual 10min and multilingual 1h setups. You can check the correct values in the templates available at ml_superb/asr1/conf/tuning
